name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    run-on: ubuntu-latest
    steps:
      - name: Print greeitng
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Good Bye"
